import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { HomePage } from '../src/components/home/home-page'
import { Header } from '../src/components/header/header'
import { Footer } from '../src/components/footer/footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home({data}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <HomePage data={data}/>
      <Footer />
    </div>
  )
}

export async function getServerSideProps() {
  const {events_categories} = await import('/data/data.json')
  return {
      props: {
          data: events_categories
      }
  }
}